version: "3.8"

services:
  neo4j:
    image: neo4j:community
    ports:

      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./scripts/neo4j_plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
